import { IExperienceEngineSessionStore, IExperienceEngineStore } from "./models";
import { ManifestClient } from "./providers/manifest-client";

export const isSSR = () => typeof window === "undefined";

export const dateNow = () => new Date();

export const now = (): EpochTimeStamp => +dateNow();

export const date = (value: number | string | Date) => new Date(value);

export const isoDate = () => dateNow().toISOString();

export const utcDate = (value: number) => date(value).toUTCString();

export const toSeconds = (ms: number) => Math.round(ms / 1000);

export const flattenObject = <T extends object>(
  obj: T = {} as T,
  prefix?: string
) =>
  objectKeys(obj).reduce((acc, k) => {
      const pre = prefix?.length ? `${prefix}.` : "";
      const value = obj[k as keyof T];

      if (isArray(value)) {
        // Preserve arrays as-is
        acc[pre + k] = value;
      } else if (isObject(value) && objectKeys(value || {}).length > 0) {
        // Continue flattening nested objects
        Object.assign(acc, flattenObject(value as T, pre + k));
      } else {
        // Assign primitive values directly
        acc[pre + k] = value;
      }

      return acc;
  }, {} as Record<string, unknown>);

/**
 * The IP address and the range's base address are both converted to binary form.
 * It then compares the specified number of prefix bits to determine if the IP
 * address falls within the range. The padStart(8, '0') ensures each octet is
 * exactly 8 bits long.  **generated by copilot
 */
export const ipRangeCheck = (ip: string, range: string) => {
  const [rangeAddress, rangePrefix] = range.split("/");
  const ipBits = ip
    .split(".")
    .map((num) => parseInt(num, 10).toString(2).padStart(8, "0"))
    .join("");
  const rangeBits = rangeAddress
    .split(".")
    .map((num) => parseInt(num, 10).toString(2).padStart(8, "0"))
    .join("");
  const prefix = parseInt(rangePrefix, 10);

  return ipBits.substring(0, prefix) === rangeBits.substring(0, prefix);
};

export const tryParse = <T>(stringified: string) => {
  try {
    // try to unstringify a found value
    return JSON.parse(stringified || "") as T;
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
  } catch (e: unknown) {
    return stringified as T | undefined;
  }
};

/** Iterate over each key in the source object and check if it exists in the obj object and has the same value */
export const objectMatches = <T extends object, S extends object>(
  obj?: T,
  source?: S
) =>
  isObject(obj) &&
  isObject(source) &&
  Object.keys(source).every(
    (key) =>
      // eslint-disable-next-line no-prototype-builtins
      obj.hasOwnProperty(key) &&
      (obj[key as keyof T] as string) === source[key as keyof S]
    // Object.prototype.hasOwnProperty.call(obj, key) && obj[key] === source[key]
  );

export const trimToLower = (val: string | number | boolean) =>
  `${val}`.trim().toLowerCase();

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const isArray = (arr: unknown): arr is Array<any> => Array.isArray(arr);
export const isNullOrUndefined = (val: unknown): val is null | undefined =>
  val === null || typeof val === "undefined";
export const isNumber = (val: unknown): val is number =>
  typeof val === "number";
export const isObject = (val: unknown) => !!val && typeof val === "object";
export const isSessionStore = (
  store:unknown
): store is IExperienceEngineSessionStore => isObject(store) && "cxpid" in store;
export const isStore = (store:unknown): store is IExperienceEngineStore =>
  isObject(store) && "cxpid" in store;
export const isString = (val: unknown): val is string =>
  typeof val === "string";
export const isStringArray = (array: unknown): array is string[] =>
  isArray(array) && array.every((element) => typeof element === "string");
export const isUndefined = (val: unknown): val is undefined =>
  typeof val === "undefined";

export const isManifestClient = (
  client: unknown
): client is ReturnType<typeof ManifestClient> =>
  isObject(client) && "get" in client;

export const objectKeys = Object.keys;
export const objectFromEntries = Object.fromEntries;
export const objectFromEntriesPreserveMultiples = <T = string>(
  entries: [string, T][] | URLSearchParamsIterator<[string, T]>
) => {
  const obj = {} as { [key: string]: T | T[] };
  for (const [param, value] of entries) {
    if (isArray(obj[param]))
      obj[param].push(...(isArray(value) ? value : [value]));
    else if (!isUndefined(obj[param]))
      obj[param] = [obj[param], ...(isArray(value) ? value : [value])];
    else obj[param] = value;
  }
  return obj;
};
export const stringify = JSON.stringify;

export const stringifyReplacer = (key: string, value: unknown) => {
  if (value instanceof Error) {
    return {
      name: value.name,
      message: value.message,
      stack: value.stack,
      cause: value.cause,
      t: now(),
    };
  }
  return value;
};

export const isObjectContentEqual = (
  a?: Record<string, unknown>,
  b?: Record<string, unknown>
) => a && b && stringify(a) === stringify(b);

export const isQuotaExceededError = (err: unknown) => {
  return (
    err instanceof DOMException &&
    // everything except Firefox
    (err.code === 22 ||
      // Firefox
      err.code === 1014 ||
      // test name field too, because code might not be present
      // everything except Firefox
      err.name === "QuotaExceededError" ||
      // Firefox
      err.name === "NS_ERROR_DOM_QUOTA_REACHED")
  );
};

export const uuid = (): string =>
  crypto.randomUUID?.() ??
  "10000000-1000-4000-8000-100000000000".replace(/[018]/g, c =>
    (+c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> +c / 4).toString(16));